apiVersion: v1
kind: ConfigMap
metadata:
  name: realrisk-flink-config
data:
  REDIS_HOST: redis.platform.svc.cluster.local
  KAFKA_BOOTSTRAP_SERVERS: kafka-bootstrap.messaging.svc.cluster.local:9092
  SCHEMA_REGISTRY_URL: http://schema-registry.messaging.svc.cluster.local:8081
