apiVersion: v1
kind: Service
metadata:
  name: realrisk-minio
spec:
  selector:
    app.kubernetes.io/name: realrisk-minio
  ports:
    - name: s3
      port: 9000
      targetPort: s3
    - name: console
      port: 9001
      targetPort: console
