resources:
  - kafka.yaml
  - nodepool.yaml
  - service-kafka-exporter.yaml
  - service-monitor-kafka-exporter.yaml
  - topics/raw-events.yaml
  - topics/raw-audit.yaml
  - topics/decision-audit.yaml
  - topics/high-risk-events.yaml
  - topics/alert-events.yaml
  - topics/alert-events-dlq.yaml
  - topics/rule-updates.yaml
