apiVersion: v1
kind: ConfigMap
metadata:
  name: realrisk-api-gateway-config
data:
  DB_URL: jdbc:postgresql://realrisk-cluster-rw.realrisk.svc.cluster.local:5432/realrisk
  SPRING_DATA_REDIS_SENTINEL_MASTER: mymaster
  SPRING_DATA_REDIS_SENTINEL_NODES: realrisk-redis-node-0.realrisk-redis-headless.realrisk.svc.cluster.local:26379,realrisk-redis-node-1.realrisk-redis-headless.realrisk.svc.cluster.local:26379,realrisk-redis-node-2.realrisk-redis-headless.realrisk.svc.cluster.local:26379
  KAFKA_BOOTSTRAP_SERVERS: realrisk-kafka-kafka-bootstrap.realrisk.svc.cluster.local:9092
  SCHEMA_REGISTRY_URL: http://realrisk-schema-registry.realrisk.svc.cluster.local:8081
  RULE_OUTBOX_POLL_INTERVAL_MS: "2000"
  RULE_OUTBOX_BATCH_SIZE: "100"
