apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: realrisk-cluster
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: realrisk
      owner: realrisk
  storage:
    size: 2Gi
