apiVersion: v1
kind: Service
metadata:
  name: realrisk-alert-service
  labels:
    app.kubernetes.io/name: realrisk-alert-service
spec:
  selector:
    app.kubernetes.io/name: realrisk-alert-service
  ports:
    - name: http
      port: 8080
      targetPort: http
