apiVersion: v1
kind: ConfigMap
metadata:
  name: realrisk-api-gateway-config
data:
  SERVER_PORT: "8080"
  DB_URL: jdbc:postgresql://postgres.invalid:5432/realrisk
  SPRING_DATA_REDIS_SENTINEL_MASTER: mymaster
  SPRING_DATA_REDIS_SENTINEL_NODES: redis.invalid:26379
  KAFKA_BOOTSTRAP_SERVERS: kafka.invalid:9092
  SCHEMA_REGISTRY_URL: http://schema-registry.invalid:8081
  RISK_WORKER_ENABLED: "false"
  RISK_WINDOW_MS: "60000"
  RISK_LIMIT: "5"
