apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: alert-events-dlq
  labels:
    strimzi.io/cluster: realrisk-kafka
spec:
  partitions: 2
  replicas: 1
  config:
    retention.ms: 604800000
