apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: decision-audit
  labels:
    strimzi.io/cluster: realrisk-kafka
spec:
  partitions: 8
  replicas: 1
  config:
    retention.ms: 7776000000
